#!/bin/sh

# gurobi
python main.py datasets/dummy0.txt -o "solver.max_time=10"
python main.py datasets/dummy1.txt -o "solver.max_time=10"
python main.py datasets/dummy2.txt -o "solver.max_time=10"
# python main.py datasets/dummy3.txt -o "solver.max_time=10"
python main.py datasets/dummy4.txt -o "solver.max_time=10"
python main.py datasets/dummy5.txt -o "solver.max_time=100"
# python main.py datasets/dummy6.txt -o "solver.max_time=10"
python main.py datasets/dummy7.txt -o "solver.max_time=100"
python main.py datasets/dummy8.txt -o "solver.max_time=200"
python main.py datasets/dummy9.txt -o "solver.max_time=200"
python main.py datasets/dummy10.txt -o "solver.max_time=200"

# greedy
python main.py datasets/dummy0.txt -H none -o "solver.max_time=10"
python main.py datasets/dummy1.txt -H none -o "solver.max_time=10"
python main.py datasets/dummy2.txt -H none -o "solver.max_time=10"
# python main.py datasets/dummy3.txt -H none -o "solver.max_time=10"
python main.py datasets/dummy4.txt -H none -o "solver.max_time=10"
python main.py datasets/dummy5.txt -H none -o "solver.max_time=100"
# python main.py datasets/dummy6.txt -H none -o "solver.max_time=10"
python main.py datasets/dummy7.txt -H none -o "solver.max_time=100"
python main.py datasets/dummy8.txt -H none -o "solver.max_time=200"
python main.py datasets/dummy9.txt -H none -o "solver.max_time=200"
python main.py datasets/dummy10.txt -H none -o "solver.max_time=200"

# local search
python main.py datasets/dummy0.txt -H ls -o "solver.max_time=10"
python main.py datasets/dummy1.txt -H ls -o "solver.max_time=10"
python main.py datasets/dummy2.txt -H ls -o "solver.max_time=10"
# python main.py datasets/dummy3.txt -H ls -o "solver.max_time=10"
python main.py datasets/dummy4.txt -H ls -o "solver.max_time=10"
python main.py datasets/dummy5.txt -H ls -o "solver.max_time=100"
# python main.py datasets/dummy6.txt -H ls -o "solver.max_time=10"
python main.py datasets/dummy7.txt -H ls -o "solver.max_time=100"
python main.py datasets/dummy8.txt -H ls -o "solver.max_time=200"
python main.py datasets/dummy9.txt -H ls -o "solver.max_time=200"
python main.py datasets/dummy10.txt -H ls -o "solver.max_time=200"

# local search multistart
python main.py datasets/dummy0.txt -H ls -m -o "solver.max_time=10"
python main.py datasets/dummy1.txt -H ls -m -o "solver.max_time=10"
python main.py datasets/dummy2.txt -H ls -m -o "solver.max_time=10"
# python main.py datasets/dummy3.txt -H ls -m -o "solver.max_time=10"
python main.py datasets/dummy4.txt -H ls -m -o "solver.max_time=10"
python main.py datasets/dummy5.txt -H ls -m -o "solver.max_time=100"
# python main.py datasets/dummy6.txt -H ls -m -o "solver.max_time=10"
python main.py datasets/dummy7.txt -H ls -m -o "solver.max_time=100"
python main.py datasets/dummy8.txt -H ls -m -o "solver.max_time=200"
python main.py datasets/dummy9.txt -H ls -m -o "solver.max_time=200"
python main.py datasets/dummy10.txt -H ls -m -o "solver.max_time=200"

# simulated annealing
python main.py datasets/dummy0.txt -H sa -o "solver.max_time=10"
python main.py datasets/dummy1.txt -H sa -o "solver.max_time=10"
python main.py datasets/dummy2.txt -H sa -o "solver.max_time=10"
# python main.py datasets/dummy3.txt -H sa-o "solver.max_time=10"
python main.py datasets/dummy4.txt -H sa -o "solver.max_time=10"
python main.py datasets/dummy5.txt -H sa -o "solver.max_time=100"
# python main.py datasets/dummy6.txt -H sa -o "solver.max_time=10"
python main.py datasets/dummy7.txt -H sa -o "solver.max_time=100"
python main.py datasets/dummy8.txt -H sa -o "solver.max_time=200"
python main.py datasets/dummy9.txt -H sa -o "solver.max_time=200"
python main.py datasets/dummy10.txt -H sa -o "solver.max_time=200"